### ISSUE TITLE
FADI installation support request from SSSA

### ISSUE THREAD

**Issue by mtskn** [cetic/fadi#129] opened 2020-07-02 10:47 UTC
Hello
Researchers from SSSA have this error when installing FADI to their machine. Please let me know if you need more information (e.g. logs from a certain service) or if you see any issues, if you can provide some possible reasons etc.

Thank you

Installed packages:

VirtualBox : 6.1.6
Minikube : 1.9.2
Helm : 3.2.0

Sys Spec:
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS" 
Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
12GiB System Memory
GM107M [GeForce GTX 950M]
80GB SSD
------------------------------------

SERVICES:
All up and running

FAILED DEPLOYMENT and REPLICA SETS:
Name: fadi-grafana, fadi-minio
Reason: MinimumReplicasUnavailable | Deployment does not have minimum availability.
Message: running "VolumeBinding" filter plugin for pod "fadi-grafana-84cd578b65-6c9k2": pod has unbound immediate PersistentVolumeClaims

FAILDED PODS: 
Name: g-ldap-sync-1587768120-swqvt / mp8lb / 6f2dq and others
Message:
/var/lib/gems/2.5.0/gems/pg-1.1.4/lib/pg.rb:56:in `initialize': could not connect to server: Connection refused (PG::ConnectionBad)
Is the server running on host "fadi-postgresql" (10.105.249.146) and accepting
TCP/IP connections on port 5432?
from /var/lib/gems/2.5.0/gems/pg-1.1.4/lib/pg.rb:56:in `new'
from /var/lib/gems/2.5.0/gems/pg-1.1.4/lib/pg.rb:56:in `connect'
from /var/lib/gems/2.5.0/gems/pg-ldap-sync-0.2.0/lib/pg_ldap_sync/application.rb:309:in `start!'
from /var/lib/gems/2.5.0/gems/pg-ldap-sync-0.2.0/lib/pg_ldap_sync/application.rb:355:in `run'
from /var/lib/gems/2.5.0/gems/pg-ldap-sync-0.2.0/exe/pg_ldap_sync:6:in `<top (required)>'
from /usr/local/bin/pg_ldap_sync:23:in `load'
from /usr/local/bin/pg_ldap_sync:23:in `<main>'

FAILED Stateful Sets:
Name: fadi-nifi, fadi-postgresql, fadi-zookeeper
Message: running "VolumeBinding" filter plugin for pod "fadi-zookeeper-0": pod has unbound immediate PersistentVolumeClaims

**Comment by alexnuttinck** [comment] 2020-07-02 13:46
Seems to be the same bug as described here: #128 
It seems also to be a bug related to the minikube storage plugin.

A quick fix is to disable persistence options on minikube. or downgrade minikube version.

**Comment by banzo** [comment] 2021-05-03 09:32
I can not reproduce the problem with recent versions of minikube, closing this.

**Closed as completed by banzo** 2021-05-03 09:32 UTC
Labels: bug
